name: Static Analysis
on:
  pull_request:
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igorshubovych/markdownlint-cli:v0.38.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint markdown files
        run: markdownlint "content/**/*.md"

      - name: Notify Discord server
        uses: Zmicier/discord-webhook@v1.0.6
        with:
          severity: info
          username: Knowledge Base Notifier
          color: '#0050B5'
          description: The Knowledge Base has been updated!
          details: "URL: https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/"
          footer: ''
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
