name: Static Analysis
on:
  pull_request:
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/igorshubovych/markdownlint-cli:v0.38.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint markdown files
        run: markdownlint "content/**/*.md"
